### ISSUE TITLE
New Shortcuts and Picture-in-Picture

### ISSUE THREAD

**Issue by GugaJedi** [FanaroEngineering/youtube_kbd_nav#29]
Some other nice shortcuts would be:

- <kbd>t</kbd> for opening a new tab directly to YouTube home
- <kbd>a</kbd> for opening an anonymous window on YouTube home
- <kbd>p</kbd> to activate *pip* (picture-in-picture).

**Comment by GugaJedi** [comment]
correction, I thing to be more useful (at list for Right hand people) is to add the pip key to 'w', I know is close to 'q' (yt home), but at list the user can be using one hand (left) on keyboard and the right hand on mouse. So the usability for me is better, you don't need to leave the mouse just to open the pip window.

**Comment by psygo** [comment]
Nice suggestions, I'm adding them to Release v2's project.

I'll have to first check that all of the suggested keys are not already taken by YouTube's native shortcuts &mdash; you can access them by pressing <kbd>Shift</kbd> + <kbd>?</kbd> on any YouTube page.

**Comment by psygo** [comment]
I broke this issue down into 3 others, so I'm closing this one.
