### ISSUE TITLE
Problems and Suggestions

### ISSUE THREAD

**Issue by GugaJedi** [FanaroEngineering/youtube_kbd_nav#30]
1. A key for switching between different logged accounts could be added.
1. <kbd>z</kbd> and <kbd>x</kbd> should scroll down/up the page when navigating through thumbnails... currently, when we go down too far, we can't what we are selecting.
1. A key to open notifications should be very nice too!

**Comment by psygo** [comment]
Scrolling is something I want to add, but it isn't that simple because the size of each thumbnail varies depending on the size of your browser window.

Since this issue contains 3 different suggestions, next time, I would suggest you create 3 separate ones instead, it's easier to manage.

**Comment by psygo** [comment]
Issue #28 already mentioned the scrolling of the page when cycling through the thumbnails.

**Comment by psygo** [comment]
I broke down this issue into 3 others, so I'm closing this one.
